activation: tanh
connectivity_matrices: null
dropout: 0.2
learning_rate: 0.0001
n_layers: 4
n_outputs: 2
network: !!python/object:binn.network.Network
  input_data: !!python/object:pandas.core.frame.DataFrame
    _flags:
      allows_duplicate_labels: true
    _metadata: &id003 []
    _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
    - !!python/tuple
      - !!python/object/apply:pandas._libs.internals._unpickle_block
        - !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple
            - 0
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple
            - 1
            - 554
          - &id002 !!python/object/apply:numpy.dtype
            args:
            - O8
            - false
            - true
            state: !!python/tuple
            - 3
            - '|'
            - null
            - null
            - null
            - -1
            - -1
            - 63
          - false
          - - P08603
            - P02671
            - P01042
            - P00450
            - P05156
            - P02452
            - P10643
            - B9A064
            - P02787
            - P00738
            - P01023
            - P04275
            - P06396
            - P03952
            - P03951
            - P04196
            - P01833
            - P35527
            - P00751
            - P19823
            - P02647
            - P05106
            - P04264
            - Q3LXA3
            - P01034
            - P08697
            - P13671
            - P35908
            - P34096
            - O00391
            - P18206
            - P0C0L4
            - P02750
            - P0CG05
            - P35579
            - P61626
            - P07996
            - Q9Y490
            - P01031
            - Q04756
            - P02768
            - P06727
            - P04114
            - P08123
            - P04731
            - P30101
            - P11047
            - P26022
            - P01009
            - P43251
            - P12259
            - P13647
            - P01834
            - P27918
            - P02774
            - O75369
            - P43652
            - P09871
            - P06681
            - O95479
            - Q08380
            - Q02985
            - P02751
            - P19827
            - P14555
            - P23142
            - P04003
            - P61981
            - P13645
            - Q14624
            - P24821
            - Q6UWP8
            - O95810
            - P00734
            - P15169
            - P09110
            - P01700
            - P98160
            - P05362
            - Q15113
            - P02649
            - P14780
            - Q02818
            - Q69YZ2
            - P37837
            - Q9Y6R7
            - Q96IY4
            - P01024
            - Q7Z4W1
            - P00742
            - P12955
            - Q14533
            - P60709
            - P02679
            - Q86UX7
            - Q96A08
            - P05787
            - P29279
            - P33151
            - Q93088
            - P10909
            - Q15582
            - P02760
            - P0C0L5
            - P02749
            - P00748
            - P02765
            - P08238
            - P80723
            - Q8TF72
            - P24752
            - Q9UGM5
            - P04075
            - P04208
            - P36955
            - P18065
            - P00747
            - Q99969
            - P68871
            - P07357
            - P35520
            - P01714
            - P06702
            - P10645
            - P28074
            - P35900
            - P14543
            - P05160
            - P16930
            - P00739
            - Q6UXB8
            - O75636
            - P02748
            - P07900
            - P00488
            - P05164
            - P21333
            - O75874
            - P04732
            - Q86VB7
            - P78417
            - iRT_protein
            - O75882
            - P01877
            - P19971
            - P01891
            - P00558
            - P20742
            - P08571
            - P35749
            - P24592
            - P80511
            - Q14520
            - P16070
            - O14791
            - P07998
            - Q16851
            - P02747
            - P51884
            - P29401
            - P17936
            - Q00796
            - O43866
            - P61769
            - P23141
            - P62805
            - P49913
            - P62736
            - Q13103
            - P04004
            - P07225
            - Q6UX71
            - P02675
            - P00736
            - P31946
            - P02743
            - P08185
            - Q15942
            - P48740
            - P14625
            - P04424
            - P69905
            - P31327
            - Q9NZP8
            - P02652
            - P11021
            - P43121
            - P05109
            - P15311
            - P01860
            - P02790
            - P15291
            - P08779
            - Q03591
            - P0DJI8
            - P02533
            - P23083
            - P05155
            - A6NCN2
            - Q58FF3
            - Q12841
            - P27797
            - Q08257
            - P01871
            - Q03154
            - P41222
            - Q04917
            - P35555
            - P00740
            - P22692
            - P08519
            - Q9H299
            - P05543
            - P02655
            - P28072
            - P05090
            - P20851
            - Q13790
            - Q8NBS9
            - P36871
            - Q9UBX5
            - Q13885
            - P81605
            - P19320
            - P06312
            - Q92954
            - P02745
            - P10809
            - P26927
            - P05546
            - P05452
            - P05121
            - P59665
            - P07358
            - P35580
            - P13611
            - P01625
            - P28799
            - P00995
            - P54108
            - O95678
            - P02753
            - P00918
            - P05451
            - P61916
            - P06703
            - Q07954
            - P63104
            - Q99436
            - P60174
            - O95445
            - P15144
            - P01008
            - P00915
            - P01876
            - P30043
            - O95497
            - P28838
            - Q9BY43
            - Q06141
            - P49747
            - P06744
            - Q02325
            - P62258
            - P05154
            - P32119
            - O75594
            - Q01995
            - Q9BWP8
            - P30086
            - P03950
            - P13987
            - P07327
            - P06737
            - P37802
            - Q9H4B7
            - P05062
            - P14314
            - P00338
            - P55290
            - P07339
            - P01598
            - Q9BYE9
            - P12109
            - P38646
            - P32754
            - Q14508
            - P02788
            - Q6ZMR3
            - P01011
            - P07237
            - P27348
            - P07451
            - P07148
            - P07360
            - P00325
            - P02144
            - P35542
            - Q15485
            - P00352
            - P01857
            - Q15848
            - Q9UHG3
            - P02730
            - P17066
            - P40925
            - P60660
            - P15151
            - P48637
            - P08294
            - P02538
            - P06733
            - Q9BXR6
            - P42765
            - Q9HDC9
            - P01604
            - P12111
            - P06331
            - P36980
            - Q9UBR2
            - P13796
            - P10451
            - P01591
            - P27105
            - P62834
            - P04040
            - P34931
            - P54652
            - Q16610
            - P25311
            - P55058
            - P11142
            - Q6GPI1
            - P22891
            - Q12805
            - A5A3E0
            - Q9UK55
            - 